using './main.bicep'

param containerRegistryName = 'okdependencytrackregistry'
param storageAccountName = 'okdtrackstorageacct'
param location = 'germanywestcentral'
param environmentName = 'ok-dependencytrack-env'
param apiServerAppName = 'ok-dependencytrack-apiserver'
param frontendAppName = 'ok-dependencytrack-frontend'
param apiServerImage = 'dependencytrack/apiserver:latest'
param frontendImage = 'dependencytrack/frontend:latest'
