using './main.bicep'

param containerRegistryName = 'ok-dependencytrackregistry'
param storageAccountName = 'ok-dtrackstorageacct'
param location = 'germanywestcentral'
param environmentName = 'ok-dependencytrack-env'
param apiServerAppName = 'ok-dependencytrack-apiserver'
param frontendAppName = 'ok-dependencytrack-frontend'
param apiServerImage = 'ok-dependencytrack/apiserver:latest'
param frontendImage = 'ok-dependencytrack/frontend:latest'
